FROM ghcr.io/nvidia/jax:base

# additional packages needed for AWS
#RUN apt-get update && apt install autoconf automake libtool -y

# AWS deps
COPY aws-install.sh /tmp
RUN chmod u+x /tmp/aws-install.sh
RUN /tmp/aws-install.sh

## SageMaker related testing
RUN pip install torch deepspeed
RUN mkdir -p /opt/ml/code
WORKDIR /opt/ml/code
RUN git clone https://github.com/EleutherAI/cookbook
COPY test-allreduce.sh /opt/ml/code/test-allreduce.sh
ENV SAGEMAKER_PROGRAM test-allreduce.sh

ENTRYPOINT ["bash", "/opt/ml/code/test-allreduce.sh"]
